/*
 * Adquirir consciencia sobre
 * nuestra respiracion es una
 * buena práctica, sin duda.
 * 
 * El aire entra
 *               El aire sale
 * Dentro de ti
 *               Fuera de ti
 *               
 *       Las cosas fluyen 
 *               
 *      
 *               El futuro es ilusión
 * El pasado es ilusión
 *               
 *     El presente es verdad 
 */
package Vista;

/**
 *
 * @author usuario
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
          
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modifklnmkjk this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrincipal01 = new javax.swing.JTextPane();
        lblYUX = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrincipal2 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuUsuario = new javax.swing.JMenu();
        mnuVentanaUsuario = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuCambiar = new javax.swing.JMenuItem();
        mnuCerrar = new javax.swing.JMenuItem();
        mnuConfig = new javax.swing.JMenu();
        itemConfigAnimo = new javax.swing.JMenuItem();
        itemConfigActividad = new javax.swing.JMenuItem();
        itemAppeal = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 350));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        btnClick.setText("HAZME CLIIIIICK");
        btnClick.setActionCommand("CMD_Click");

        jScrollPane1.setBorder(null);

        txtPrincipal01.setBackground(new java.awt.Color(240, 240, 240));
        txtPrincipal01.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        txtPrincipal01.setText("Hola! Espero estés bien.\nTe bienvengo a la ventana principal de YUX\ndesde acá podrás acceder, a través de la Barra de Menú dispuesta arriba\na la ventana de usuario, en la cual te puedes registrar, ingresar o solicitar\nuna nueva contrasenha.\nUna vez hagas eso, podrás acceder a las demás opciones de esta aplicación");
        jScrollPane1.setViewportView(txtPrincipal01);

        lblYUX.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        lblYUX.setForeground(new java.awt.Color(0, 204, 204));
        lblYUX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYUX.setText("YUX");

        jScrollPane2.setBorder(null);

        txtPrincipal2.setBackground(new java.awt.Color(240, 240, 240));
        txtPrincipal2.setFont(new java.awt.Font("Source Code Pro Black", 2, 12)); // NOI18N
        txtPrincipal2.setText("Hola! Espero estés bien.\nTe bienvengo a la ventana principal de YUX\ndesde acá podrás acceder, a través de la Barra de Menú dispuesta arriba\na la ventana de usuario, en la cual te puedes registrar, ingresar o solicitar\nuna nueva contrasenha.\nUna vez hagas eso, podrás acceder a las demás opciones de esta aplicación");
        jScrollPane2.setViewportView(txtPrincipal2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblYUX, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnClick)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblYUX, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 470, 245);

        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Versión inicial, ventana  de Configuración no habilitada");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 261, 14);

        /*
        int a;
        a = (int)(Math.random()*10);
        String url;
        switch(a){
            case 1:
            url = "/otrogato.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 2:
            url = "/gato.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 3:
            url = "/GATOO.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 4:
            url = "/masgato.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 5:
            url = "/caracogato.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 6:
            url = "/secciongato.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 7:
            url = "/plalo.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 8:
            url = "/jake.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 9:
            url = "/log.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
            case 10:
            url = "/huefvo.jpg";
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(url)));
            break;
        }
        */
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 280);

        mnuUsuario.setText("Usuario");
        mnuUsuario.setActionCommand("CMD_mnuUsuarioItem");
        mnuUsuario.setEnabled(false);

        mnuVentanaUsuario.setText("Ventana de Usuario");
        mnuVentanaUsuario.setActionCommand("CMD_Ventana de Usuario");
        mnuUsuario.add(mnuVentanaUsuario);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.setActionCommand("CMD_Usuarios");
        mnuUsuario.add(mnuUsuarios);

        mnuCambiar.setText("Cambiar Sesión");
        mnuCambiar.setActionCommand("CMD_Cambiar Sesión");
        mnuUsuario.add(mnuCambiar);

        mnuCerrar.setText("Cerrar Sesión");
        mnuCerrar.setActionCommand("CMD_Cerrar Sesión");
        mnuUsuario.add(mnuCerrar);

        jMenuBar1.add(mnuUsuario);

        mnuConfig.setText("Configuración");
        mnuConfig.setActionCommand("CMD_Configuración");
        mnuConfig.setEnabled(false);

        itemConfigAnimo.setText("Animo");
        itemConfigAnimo.setActionCommand("CMD_ConfigAnimo");
        mnuConfig.add(itemConfigAnimo);

        itemConfigActividad.setText("Actividad");
        itemConfigActividad.setActionCommand("CMD_ConfigActividad");
        itemConfigActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConfigActividadActionPerformed(evt);
            }
        });
        mnuConfig.add(itemConfigActividad);

        itemAppeal.setText("Appeal");
        mnuConfig.add(itemAppeal);

        jMenuBar1.add(mnuConfig);

        mnuAyuda.setText("Ayuda!");
        mnuAyuda.setActionCommand("CMD_Ayuda!");

        jMenuItem1.setText("Aun no está habilitada la ayuda :/");
        mnuAyuda.add(jMenuItem1);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemConfigActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConfigActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemConfigActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnClick;
    private javax.swing.JMenuItem itemAppeal;
    public javax.swing.JMenuItem itemConfigActividad;
    public javax.swing.JMenuItem itemConfigAnimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblYUX;
    public javax.swing.JMenu mnuAyuda;
    public javax.swing.JMenuItem mnuCambiar;
    public javax.swing.JMenuItem mnuCerrar;
    public javax.swing.JMenu mnuConfig;
    public javax.swing.JMenu mnuUsuario;
    public javax.swing.JMenu mnuUsuarios;
    public javax.swing.JMenuItem mnuVentanaUsuario;
    private javax.swing.JTextPane txtPrincipal01;
    private javax.swing.JTextPane txtPrincipal2;
    // End of variables declaration//GEN-END:variables
}
